#include "./functions/change_tetromino_position.asm"
#include "./functions/rotate_tetromino.asm"
#include "./functions/set_tetromino.asm"
#include "./functions/delay.asm"
#include "./functions/copy_next_to_current.asm"